### ISSUE TITLE
Config should be done via config file, with a default (and overridable) CLI argument

### ISSUE THREAD

**Issue by ChrisMacNaughton** [ChrisMacNaughton/Mjolnir#48]
Idea config

```toml
[mjolnir]
masters = [  # Masters are $IP:$HTTP_PORT:$ZMQ_PORT
    "10.0.0.10:11011:12011",
    "10.0.0.11:11011:12011",
    "10.0.0.12:11011:12011"
]

[[pipelines]]

[[pipelines.alert]]
type = "alertmanager" # The type of alert to match on
name = "full-disk" # Optionally, the name that the alert provides

# actions is an array of remediations that will be attempted, in order
# and type matches the plugin name to execute
actions = [
    {
        type = "clean_disk"
    }, {
        type = "page-on-call",
    }
]
```

for something like this JSON representation:
```json
{
	"mjolnir": {
		"masters": [
			"10.0.0.10:11011:12011",
			"10.0.0.11:11011:12011",
			"10.0.0.12:11011:12011"
		]
	},
	"pipelines": [{
		"actions": [
			"clean_disk",
			"page-on-call"
		],
		"alert": {
			"type": "alertmanager",
			"name": "full-disk"
		}
	}]
}
```
