### ISSUE TITLE
Overridable config

### ISSUE THREAD

**Issue by ChrisMacNaughton** [ChrisMacNaughton/Mjolnir#51]
Mjolnir < Agent / Master

Any configuration option should be overridable by a more specific section

```toml
[mjolnir]
key_path = "/var/mjolnir/keys"

[agent]
key_path = "/var/mjolnir/agent/keys"
```

For a master running with the above config, the keys will be expected at `/var/mjolnir/keys` while an agent would expect them at `/var/mjolnir/agent/keys`
